### ISSUE TITLE
Don't mirror well known labels/annotations used for ownership tracking.

### ISSUE THREAD

**Issue by cehoffman** [1Password/onepassword-operator#84]
### Summary

#43 added labels and annotation propagation from the OnePasswordItem to the resulting Secret. For certain tooling, like ArgoCD, which uses the label `app.kubernetes.io/instance` and/or annotation `argocd.argoproj.io/tracking-id` to track ownership this results in the tool wanting to delete the secret as it sees this no owner reference resource as orphaned.

### Use cases

Allow upgrading the operator for users of example tooling. As it is now upgrading the tooling will result breaking functionality as deployment tools will delete the secrets resulting in a period of downtime until the operator repopulates the secret. Setting owner reference would also better surface resource relationships.

### Proposed solution

To combat this, the OnePasswordItem should set populate the owner references field of the secret with the controlling OnePasswordItem so the object is not viewed as orphaned. Optionally not copying these specific labels/annotations would solve the problem.

### Is there a workaround to accomplish this today?

None

### References & Prior Work

* 
*

**Comment by denismorozov** [comment]
Hi team, I also use ArgoCD and have the same issue. I am moving some of my secrets from SealedSecrets to the 1PasswordOperator and this is a pain point currently - all applications appear out of sync because the 1Password created secrets appear detached. SealedSecrets's secrets on the other hand are correctly linked using owner references.

@cehoffman FYI because all my secrets are managed by SealedSecrets and 1PasswordOperator, I was able to get away with adding an [ArgoCD resource exclusion](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion) for all secrets:

```
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - Secret
      clusters:
      - "*"
```

However, I do miss being able to see the secrets in ArgoCD.
